### ISSUE TITLE
Jutho/TensorToolbox.jl

### ISSUE THREAD

**Issue by montyvesselinov** [lanaperisa/Tensors.jl#2]
Have you made comparisons with https://github.com/Jutho/TensorToolbox.jl? There are conflicting names ...

**Comment by lanaperisa** [comment]
No, my TensorToolbox.jl is a registered Julia package, and https://github.com/Jutho/TensorToolbox.jl works quite differently, so I'm not sure that both can be used for same problems anyway.

**Comment by montyvesselinov** [comment]
Thank you very much!
