### ISSUE TITLE
https://github.com/KristofferC/Tensors.jl

### ISSUE THREAD

**Issue by montyvesselinov** [lanaperisa/Tensors.jl#3]
Tensors is already registered to this https://gitohub.com/KristofferC/Tensors.jl

Can you rename your repo so i can use both in one installation?

**Comment by lanaperisa** [comment]
My Tensors.jl is just an old version of my TensorToolbox.jl, so use TensorToolbox.jl.

**Comment by montyvesselinov** [comment]
Thank you very much!
